theme: osuny
pagination:
  pagerSize: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false
  keycdn: 
    url: https://osunystaging-1b4da.kxcdn.com
  